"""update models

Revision ID: 93a6592270d5
Revises: b2b566d8d8b9
Create Date: 2024-03-03 21:48:29.827354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a6592270d5'
down_revision: Union[str, None] = 'b2b566d8d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter', sa.TEXT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter'),
    schema='public'
    )
    op.create_index(op.f('ix_public_discord_adds_id'), 'discord_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_discord_adds_user_id'), 'discord_adds', ['user_id'], unique=False, schema='public')
    op.create_table('users_pointers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transport_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('numbers_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('homes_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('business_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('clothes_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('weapon_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('loot_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('services_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('global_pointer', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_pointers_id'), 'users_pointers', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_pointers_user_id'), 'users_pointers', ['user_id'], unique=False, schema='public')
    op.drop_index('ix_public_weapon_adds_id', table_name='weapon_adds')
    op.drop_index('ix_public_weapon_adds_user_id', table_name='weapon_adds')
    op.drop_table('weapon_adds')
    op.drop_index('ix_public_user_pointers_id', table_name='user_pointers')
    op.drop_index('ix_public_user_pointers_user_id', table_name='user_pointers')
    op.drop_table('user_pointers')
    op.drop_index('ix_public_services_adds_id', table_name='services_adds')
    op.drop_index('ix_public_services_adds_user_id', table_name='services_adds')
    op.drop_table('services_adds')
    op.drop_index('ix_public_clothes_adds_id', table_name='clothes_adds')
    op.drop_index('ix_public_clothes_adds_user_id', table_name='clothes_adds')
    op.drop_table('clothes_adds')
    op.drop_index('ix_public_numbers_adds_id', table_name='numbers_adds')
    op.drop_index('ix_public_numbers_adds_user_id', table_name='numbers_adds')
    op.drop_table('numbers_adds')
    op.drop_index('ix_public_transport_adds_id', table_name='transport_adds')
    op.drop_index('ix_public_transport_adds_user_id', table_name='transport_adds')
    op.drop_table('transport_adds')
    op.drop_index('ix_public_homes_adds_id', table_name='homes_adds')
    op.drop_index('ix_public_homes_adds_user_id', table_name='homes_adds')
    op.drop_table('homes_adds')
    op.drop_index('ix_public_crafts_id', table_name='crafts')
    op.drop_table('crafts')
    op.drop_index('ix_public_loot_adds_id', table_name='loot_adds')
    op.drop_index('ix_public_loot_adds_user_id', table_name='loot_adds')
    op.drop_table('loot_adds')
    op.drop_index('ix_public_global_adds_id', table_name='global_adds')
    op.drop_index('ix_public_global_adds_user_id', table_name='global_adds')
    op.drop_table('global_adds')
    op.drop_index('ix_public_car_tags_car_id', table_name='car_tags')
    op.drop_index('ix_public_car_tags_id', table_name='car_tags')
    op.drop_index('ix_public_car_tags_tag', table_name='car_tags')
    op.drop_table('car_tags')
    op.drop_index('ix_public_lootboxes_id', table_name='lootboxes')
    op.drop_table('lootboxes')
    op.drop_index('ix_public_business_adds_id', table_name='business_adds')
    op.drop_index('ix_public_business_adds_user_id', table_name='business_adds')
    op.drop_table('business_adds')
    op.alter_column('cars', 'tank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'cars', ['image_link'], schema='public')
    op.create_unique_constraint(None, 'cars', ['name'], schema='public')
    op.create_unique_constraint(None, 'fishing', ['depth'], schema='public')
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False))
    op.create_unique_constraint(None, 'notifications', ['user_id', 'tag'], schema='public')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('rent_adds', 'is_deleted')
    op.alter_column('users', 'discord_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['telegram_id'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.alter_column('users', 'discord_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('rent_adds', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', schema='public', type_='unique')
    op.drop_column('notifications', 'created_at')
    op.drop_constraint(None, 'fishing', schema='public', type_='unique')
    op.drop_constraint(None, 'cars', schema='public', type_='unique')
    op.drop_constraint(None, 'cars', schema='public', type_='unique')
    op.alter_column('cars', 'tank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('business_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='business_adds_pkey')
    )
    op.create_index('ix_public_business_adds_user_id', 'business_adds', ['user_id'], unique=False)
    op.create_index('ix_public_business_adds_id', 'business_adds', ['id'], unique=False)
    op.create_table('lootboxes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lootboxes_pkey')
    )
    op.create_index('ix_public_lootboxes_id', 'lootboxes', ['id'], unique=False)
    op.create_table('car_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car_tags_pkey')
    )
    op.create_index('ix_public_car_tags_tag', 'car_tags', ['tag'], unique=False)
    op.create_index('ix_public_car_tags_id', 'car_tags', ['id'], unique=False)
    op.create_index('ix_public_car_tags_car_id', 'car_tags', ['car_id'], unique=False)
    op.create_table('global_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='global_adds_pkey')
    )
    op.create_index('ix_public_global_adds_user_id', 'global_adds', ['user_id'], unique=False)
    op.create_index('ix_public_global_adds_id', 'global_adds', ['id'], unique=False)
    op.create_table('loot_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='loot_adds_pkey')
    )
    op.create_index('ix_public_loot_adds_user_id', 'loot_adds', ['user_id'], unique=False)
    op.create_index('ix_public_loot_adds_id', 'loot_adds', ['id'], unique=False)
    op.create_table('crafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crafts_pkey')
    )
    op.create_index('ix_public_crafts_id', 'crafts', ['id'], unique=False)
    op.create_table('homes_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='homes_adds_pkey')
    )
    op.create_index('ix_public_homes_adds_user_id', 'homes_adds', ['user_id'], unique=False)
    op.create_index('ix_public_homes_adds_id', 'homes_adds', ['id'], unique=False)
    op.create_table('transport_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='transport_adds_pkey')
    )
    op.create_index('ix_public_transport_adds_user_id', 'transport_adds', ['user_id'], unique=False)
    op.create_index('ix_public_transport_adds_id', 'transport_adds', ['id'], unique=False)
    op.create_table('numbers_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='numbers_adds_pkey')
    )
    op.create_index('ix_public_numbers_adds_user_id', 'numbers_adds', ['user_id'], unique=False)
    op.create_index('ix_public_numbers_adds_id', 'numbers_adds', ['id'], unique=False)
    op.create_table('clothes_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clothes_adds_pkey')
    )
    op.create_index('ix_public_clothes_adds_user_id', 'clothes_adds', ['user_id'], unique=False)
    op.create_index('ix_public_clothes_adds_id', 'clothes_adds', ['id'], unique=False)
    op.create_table('services_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='services_adds_pkey')
    )
    op.create_index('ix_public_services_adds_user_id', 'services_adds', ['user_id'], unique=False)
    op.create_index('ix_public_services_adds_id', 'services_adds', ['id'], unique=False)
    op.create_table('user_pointers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transport_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numbers_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homes_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clothes_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weapon_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loot_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('services_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('global_pointer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pointers_pkey')
    )
    op.create_index('ix_public_user_pointers_user_id', 'user_pointers', ['user_id'], unique=False)
    op.create_index('ix_public_user_pointers_id', 'user_pointers', ['id'], unique=False)
    op.create_table('weapon_adds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='weapon_adds_pkey')
    )
    op.create_index('ix_public_weapon_adds_user_id', 'weapon_adds', ['user_id'], unique=False)
    op.create_index('ix_public_weapon_adds_id', 'weapon_adds', ['id'], unique=False)
    op.drop_index(op.f('ix_public_users_pointers_user_id'), table_name='users_pointers', schema='public')
    op.drop_index(op.f('ix_public_users_pointers_id'), table_name='users_pointers', schema='public')
    op.drop_table('users_pointers', schema='public')
    op.drop_index(op.f('ix_public_discord_adds_user_id'), table_name='discord_adds', schema='public')
    op.drop_index(op.f('ix_public_discord_adds_id'), table_name='discord_adds', schema='public')
    op.drop_table('discord_adds', schema='public')
    # ### end Alembic commands ###
