"""adding adds_history

Revision ID: dea1aff348f0
Revises: 93a6592270d5
Create Date: 2024-03-05 02:14:43.114457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea1aff348f0'
down_revision: Union[str, None] = '93a6592270d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_discord_adds',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.TEXT(), nullable=False),
    sa.Column('sent_datetime', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sent_discord_adds_id'), 'sent_discord_adds', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sent_discord_adds_id'), table_name='sent_discord_adds', schema='public')
    op.drop_table('sent_discord_adds', schema='public')
    # ### end Alembic commands ###
