"""changing structure

Revision ID: ecc7d61b87ef
Revises: dea1aff348f0
Create Date: 2024-05-06 21:04:00.457635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc7d61b87ef'
down_revision: Union[str, None] = 'dea1aff348f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_discord_adds', sa.Column('channel_id', sa.TEXT(), nullable=False))
    op.add_column('sent_discord_adds', sa.Column('is_reaction', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent_discord_adds', 'is_reaction')
    op.drop_column('sent_discord_adds', 'channel_id')
    # ### end Alembic commands ###
