"""changing orm models

Revision ID: 73042077dcfd
Revises: ac6836378965
Create Date: 2024-08-26 18:02:28.716647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73042077dcfd'
down_revision: Union[str, None] = 'ac6836378965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'businesses', ['user_id', 'name'], schema='public')
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('cars', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('cars', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('discord_adds', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'discord_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('fishing', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('fishing', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('gangs', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('homes', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'homes', ['user_id', 'name'], schema='public')
    op.create_foreign_key(None, 'homes', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'rent_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('sent_discord_adds', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('sent_discord_adds', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'sent_discord_adds', ['message_id', 'channel_id'], schema='public')
    op.create_foreign_key(None, 'sent_discord_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('sent_discord_adds', 'sent_datetime')
    op.add_column('users_pointers', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'users_pointers', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_pointers', schema='public', type_='foreignkey')
    op.drop_column('users_pointers', 'created_at')
    op.add_column('sent_discord_adds', sa.Column('sent_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sent_discord_adds', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sent_discord_adds', schema='public', type_='unique')
    op.drop_column('sent_discord_adds', 'updated_at')
    op.drop_column('sent_discord_adds', 'created_at')
    op.drop_constraint(None, 'rent_adds', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'notifications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'homes', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'homes', schema='public', type_='unique')
    op.drop_column('homes', 'created_at')
    op.drop_column('gangs', 'created_at')
    op.drop_column('fishing', 'updated_at')
    op.drop_column('fishing', 'created_at')
    op.drop_constraint(None, 'discord_adds', schema='public', type_='foreignkey')
    op.drop_column('discord_adds', 'created_at')
    op.drop_column('cars', 'updated_at')
    op.drop_column('cars', 'created_at')
    op.drop_constraint(None, 'businesses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'businesses', schema='public', type_='unique')
    op.drop_column('businesses', 'created_at')
    # ### end Alembic commands ###
