"""initial migration

Revision ID: b2b566d8d8b9
Revises: 
Create Date: 2024-01-29 01:03:37.423578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2b566d8d8b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_business_adds_id'), 'business_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_business_adds_user_id'), 'business_adds', ['user_id'], unique=False, schema='public')
    op.create_table('car_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('car_id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_car_tags_car_id'), 'car_tags', ['car_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_car_tags_id'), 'car_tags', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_car_tags_tag'), 'car_tags', ['tag'], unique=False, schema='public')
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('classification', sa.TEXT(), nullable=False),
    sa.Column('max_speed', sa.INTEGER(), nullable=False),
    sa.Column('is_body_kit', sa.BOOLEAN(), nullable=False),
    sa.Column('trunk', sa.INTEGER(), nullable=False),
    sa.Column('image_link', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_cars_id'), 'cars', ['id'], unique=False, schema='public')
    op.create_table('clothes_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_clothes_adds_id'), 'clothes_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_clothes_adds_user_id'), 'clothes_adds', ['user_id'], unique=False, schema='public')
    op.create_table('crafts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('photo', sa.TEXT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_crafts_id'), 'crafts', ['id'], unique=False, schema='public')
    op.create_table('fishing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('depth', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_fishing_id'), 'fishing', ['id'], unique=False, schema='public')
    op.create_table('global_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_global_adds_id'), 'global_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_global_adds_user_id'), 'global_adds', ['user_id'], unique=False, schema='public')
    op.create_table('homes_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_homes_adds_id'), 'homes_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_homes_adds_user_id'), 'homes_adds', ['user_id'], unique=False, schema='public')
    op.create_table('loot_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_loot_adds_id'), 'loot_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_loot_adds_user_id'), 'loot_adds', ['user_id'], unique=False, schema='public')
    op.create_table('lootboxes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('photo', sa.TEXT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_lootboxes_id'), 'lootboxes', ['id'], unique=False, schema='public')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_notifications_id'), 'notifications', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='public')
    op.create_table('numbers_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_numbers_adds_id'), 'numbers_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_numbers_adds_user_id'), 'numbers_adds', ['user_id'], unique=False, schema='public')
    op.create_table('rent_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('number_of_gm', sa.INTEGER(), nullable=False),
    sa.Column('add_text', sa.TEXT(), nullable=False),
    sa.Column('contact_link', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_check', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_rent_adds_id'), 'rent_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_rent_adds_number_of_gm'), 'rent_adds', ['number_of_gm'], unique=False, schema='public')
    op.create_index(op.f('ix_public_rent_adds_user_id'), 'rent_adds', ['user_id'], unique=False, schema='public')
    op.create_table('services_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_services_adds_id'), 'services_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_services_adds_user_id'), 'services_adds', ['user_id'], unique=False, schema='public')
    op.create_table('transport_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_transport_adds_id'), 'transport_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_transport_adds_user_id'), 'transport_adds', ['user_id'], unique=False, schema='public')
    op.create_table('user_pointers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transport_pointer', sa.INTEGER(), nullable=False),
    sa.Column('numbers_pointer', sa.INTEGER(), nullable=False),
    sa.Column('homes_pointer', sa.INTEGER(), nullable=False),
    sa.Column('business_pointer', sa.INTEGER(), nullable=False),
    sa.Column('clothes_pointer', sa.INTEGER(), nullable=False),
    sa.Column('weapon_pointer', sa.INTEGER(), nullable=False),
    sa.Column('loot_pointer', sa.INTEGER(), nullable=False),
    sa.Column('services_pointer', sa.INTEGER(), nullable=False),
    sa.Column('global_pointer', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_pointers_id'), 'user_pointers', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_pointers_user_id'), 'user_pointers', ['user_id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('telegram_name', sa.TEXT(), nullable=False),
    sa.Column('discord_token', sa.TEXT(), nullable=False),
    sa.Column('is_have_premium', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_telegram_id'), 'users', ['telegram_id'], unique=False, schema='public')
    op.create_table('weapon_adds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_sent', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_weapon_adds_id'), 'weapon_adds', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_weapon_adds_user_id'), 'weapon_adds', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_weapon_adds_user_id'), table_name='weapon_adds', schema='public')
    op.drop_index(op.f('ix_public_weapon_adds_id'), table_name='weapon_adds', schema='public')
    op.drop_table('weapon_adds', schema='public')
    op.drop_index(op.f('ix_public_users_telegram_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_user_pointers_user_id'), table_name='user_pointers', schema='public')
    op.drop_index(op.f('ix_public_user_pointers_id'), table_name='user_pointers', schema='public')
    op.drop_table('user_pointers', schema='public')
    op.drop_index(op.f('ix_public_transport_adds_user_id'), table_name='transport_adds', schema='public')
    op.drop_index(op.f('ix_public_transport_adds_id'), table_name='transport_adds', schema='public')
    op.drop_table('transport_adds', schema='public')
    op.drop_index(op.f('ix_public_services_adds_user_id'), table_name='services_adds', schema='public')
    op.drop_index(op.f('ix_public_services_adds_id'), table_name='services_adds', schema='public')
    op.drop_table('services_adds', schema='public')
    op.drop_index(op.f('ix_public_rent_adds_user_id'), table_name='rent_adds', schema='public')
    op.drop_index(op.f('ix_public_rent_adds_number_of_gm'), table_name='rent_adds', schema='public')
    op.drop_index(op.f('ix_public_rent_adds_id'), table_name='rent_adds', schema='public')
    op.drop_table('rent_adds', schema='public')
    op.drop_index(op.f('ix_public_numbers_adds_user_id'), table_name='numbers_adds', schema='public')
    op.drop_index(op.f('ix_public_numbers_adds_id'), table_name='numbers_adds', schema='public')
    op.drop_table('numbers_adds', schema='public')
    op.drop_index(op.f('ix_public_notifications_user_id'), table_name='notifications', schema='public')
    op.drop_index(op.f('ix_public_notifications_id'), table_name='notifications', schema='public')
    op.drop_table('notifications', schema='public')
    op.drop_index(op.f('ix_public_lootboxes_id'), table_name='lootboxes', schema='public')
    op.drop_table('lootboxes', schema='public')
    op.drop_index(op.f('ix_public_loot_adds_user_id'), table_name='loot_adds', schema='public')
    op.drop_index(op.f('ix_public_loot_adds_id'), table_name='loot_adds', schema='public')
    op.drop_table('loot_adds', schema='public')
    op.drop_index(op.f('ix_public_homes_adds_user_id'), table_name='homes_adds', schema='public')
    op.drop_index(op.f('ix_public_homes_adds_id'), table_name='homes_adds', schema='public')
    op.drop_table('homes_adds', schema='public')
    op.drop_index(op.f('ix_public_global_adds_user_id'), table_name='global_adds', schema='public')
    op.drop_index(op.f('ix_public_global_adds_id'), table_name='global_adds', schema='public')
    op.drop_table('global_adds', schema='public')
    op.drop_index(op.f('ix_public_fishing_id'), table_name='fishing', schema='public')
    op.drop_table('fishing', schema='public')
    op.drop_index(op.f('ix_public_crafts_id'), table_name='crafts', schema='public')
    op.drop_table('crafts', schema='public')
    op.drop_index(op.f('ix_public_clothes_adds_user_id'), table_name='clothes_adds', schema='public')
    op.drop_index(op.f('ix_public_clothes_adds_id'), table_name='clothes_adds', schema='public')
    op.drop_table('clothes_adds', schema='public')
    op.drop_index(op.f('ix_public_cars_id'), table_name='cars', schema='public')
    op.drop_table('cars', schema='public')
    op.drop_index(op.f('ix_public_car_tags_tag'), table_name='car_tags', schema='public')
    op.drop_index(op.f('ix_public_car_tags_id'), table_name='car_tags', schema='public')
    op.drop_index(op.f('ix_public_car_tags_car_id'), table_name='car_tags', schema='public')
    op.drop_table('car_tags', schema='public')
    op.drop_index(op.f('ix_public_business_adds_user_id'), table_name='business_adds', schema='public')
    op.drop_index(op.f('ix_public_business_adds_id'), table_name='business_adds', schema='public')
    op.drop_table('business_adds', schema='public')
    # ### end Alembic commands ###
