"""adding func now to last_sent

Revision ID: cdc23f62a683
Revises: 73042077dcfd
Create Date: 2024-09-13 14:11:04.572157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc23f62a683'
down_revision: Union[str, None] = '73042077dcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('businesses_user_id_fkey', 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('discord_adds_user_id_fkey', 'discord_adds', type_='foreignkey')
    op.create_foreign_key(None, 'discord_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('homes_user_id_fkey', 'homes', type_='foreignkey')
    op.create_foreign_key(None, 'homes', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('rent_adds_user_id_fkey', 'rent_adds', type_='foreignkey')
    op.create_foreign_key(None, 'rent_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sent_discord_adds_user_id_fkey', 'sent_discord_adds', type_='foreignkey')
    op.create_foreign_key(None, 'sent_discord_adds', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_pointers_user_id_fkey', 'users_pointers', type_='foreignkey')
    op.create_foreign_key(None, 'users_pointers', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_pointers', schema='public', type_='foreignkey')
    op.create_foreign_key('users_pointers_user_id_fkey', 'users_pointers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sent_discord_adds', schema='public', type_='foreignkey')
    op.create_foreign_key('sent_discord_adds_user_id_fkey', 'sent_discord_adds', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rent_adds', schema='public', type_='foreignkey')
    op.create_foreign_key('rent_adds_user_id_fkey', 'rent_adds', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', schema='public', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'homes', schema='public', type_='foreignkey')
    op.create_foreign_key('homes_user_id_fkey', 'homes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'discord_adds', schema='public', type_='foreignkey')
    op.create_foreign_key('discord_adds_user_id_fkey', 'discord_adds', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'businesses', schema='public', type_='foreignkey')
    op.create_foreign_key('businesses_user_id_fkey', 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
