"""some updates

Revision ID: f641426a1444
Revises: ecc7d61b87ef
Create Date: 2024-08-25 22:12:47.142746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f641426a1444'
down_revision: Union[str, None] = 'ecc7d61b87ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('profit', sa.INTEGER(), nullable=False),
    sa.Column('tasks_count', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_businesses_id'), 'businesses', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_businesses_user_id'), 'businesses', ['user_id'], unique=False, schema='public')
    op.create_table('gangs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('capt_chat_id', sa.TEXT(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_gangs_id'), 'gangs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_gangs_user_id'), 'gangs', ['user_id'], unique=False, schema='public')
    op.create_table('homes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('expenses', sa.INTEGER(), nullable=True),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_homes_id'), 'homes', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_homes_user_id'), 'homes', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_homes_user_id'), table_name='homes', schema='public')
    op.drop_index(op.f('ix_public_homes_id'), table_name='homes', schema='public')
    op.drop_table('homes', schema='public')
    op.drop_index(op.f('ix_public_gangs_user_id'), table_name='gangs', schema='public')
    op.drop_index(op.f('ix_public_gangs_id'), table_name='gangs', schema='public')
    op.drop_table('gangs', schema='public')
    op.drop_index(op.f('ix_public_businesses_user_id'), table_name='businesses', schema='public')
    op.drop_index(op.f('ix_public_businesses_id'), table_name='businesses', schema='public')
    op.drop_table('businesses', schema='public')
    # ### end Alembic commands ###
